version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    networks:
      - net
    ports:
      - 1883:1883
    volumes:
      - ./etc/mosquitto:/etc/mosquitto/
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.26.3
    hostname: telegraf
    user: telegraf
    restart: always
    command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
    networks:
      - net
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    environment:
      - "TZ=${TIMEZONE}"
    ports:
      - 8094:8094

  influxdb:
    image: influxdb:2.7.1
    hostname: influxdb
    restart: always
    networks:
      - net
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
      #- ./init-influxdb.sh:/docker-entrypoint-initdb.d/init-influxdb.sh
      #- influxdb_marker:/var/lib/influxdb/.initialized
    environment:
      - 'TZ=${TIMEZONE}'
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    depends_on:
      - telegraf

  kapacitor:
    image: kapacitor:1.6.6
    hostname: kapacitor
    restart: always
    networks:
      - net
    ports:
      - 9092:9092
    environment:
      - "TZ=${TIMEZONE}"
      - KAPACITOR_HOSTNAME=${KAPACITOR_HOSTNAME}
      - KAPACITOR_INFLUXDB_0_URLS_0=${KAPACITOR_INFLUXDB_0_URLS_0}
    depends_on:
      - influxdb

  chronograf:
    image: chronograf:1.10.1
    hostname: chronograf
    restart: always
    networks:
      - net
    ports:
      - 8888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
      - kapacitor
    environment:
      - "TZ=${TIMEZONE}"
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

networks:
  net:
    driver: bridge

volumes:
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local
  influxdb_data:
    driver: local
  chronograf_data:
    driver: local
