version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    hostname: mosquitto
    restart: always
    user: 1883:1883
    environment:
      - PUID=1883
      - PGID=1883
    build:
      context: ./etc/mosquitto/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/:rw

  kapacitor:
    image: kapacitor:1.6.6
    hostname: kapacitor
    restart: always
    build:
      context: ./etc/kapacitor/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - 9092:9092
    depends_on:
      - influxdb

  chronograf:
    image: chronograf:1.10.1
    hostname: chronograf
    restart: always
    networks:
      - net
    ports:
      - 8888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
      - shared_data:/shared
    depends_on:
      - influxdb
      - kapacitor
    environment:
      - TZ=${TIMEZONE}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - KAPACITOR_URL=${KAPACITOR_URL}

  telegraf:
    build:
      context: ./etc/telegraf/
      dockerfile: Dockerfile
    hostname: telegraf
    user: telegraf
    restart: always
    networks:
      - net
    volumes:
      - shared_data:/shared
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 8094:8094
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7.1
    hostname: influxdb
    restart: always
    build:
      context: ./etc/influxdb/
      dockerfile: Dockerfile
      args:
        - TZ=${TIMEZONE}
        - DATABASE=${INFLUXDB_DATABASE}
        - USERNAME=${INFLUXDB_USERNAME}
        - PASSWORD=${INFLUXDB_PASSWORD}
        - ORG=${INFLUXDB_ORG}
        - URL=${INFLUXDB_URL}
        - TOKEN=${INFLUXDB_TOKEN}
        - HTTP_AUTH_ENABLED=true
    environment:
      - TZ=${TIMEZONE}
      - INFLUXDB_DATABASE=${INFLUXDB_DATABASE}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - net
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
      - shared_data:/shared

networks:
  net:
    driver: bridge

volumes:
  
  mosquitto_data:
    driver: local
  chronograf_data:
    driver: local
  influxdb_data:
    driver: local
  shared_data:
    driver: local