version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    hostname: mosquitto
    restart: always
    user: 1883:1883
    environment:
      - PUID=1883
      - PGID=1883
    build:
      context: ./etc/mosquitto/
      dockerfile: Dockerfile
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/:rw
    networks:
      - net

  chronograf:
    image: chronograf:1.10.1
    hostname: chronograf
    restart: always
    build:
      context: ./etc/chronograf/
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
      - shared_data:/shared
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - net
    env_file:
      - .env

  telegraf:
    image: telegraf:1.20.2
    hostname: telegraf
    user: telegraf
    restart: always
    command: telegraf --config="/shared/telegraf/telegraf.conf" --watch-config="inotify"
    volumes:
      - shared_data:/shared/:rw
    ports:
      - 8094:8094
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - net
    env_file:
      - .env

  influxdb:
    image: influxdb:2.7.1
    hostname: influxdb
    restart: always
    build:
      context: ./etc/influxdb/
      dockerfile: Dockerfile
      args:
        - TZ=${TIMEZONE}
        - DATABASE=${INFLUXDB_DATABASE}
        - USERNAME=${INFLUXDB_USERNAME}
        - PASSWORD=${INFLUXDB_PASSWORD}
        - ORG=${INFLUXDB_ORG}
        - URL=${INFLUXDB_URL}
        - HTTP_AUTH_ENABLED=true
    healthcheck:
      test: test -f /shared/token || exit 1
      timeout: 1m
      retries: 10
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
      - shared_data:/shared/:rw
    networks:
      - net
    env_file:
      - .env

networks:
  net:
    driver: bridge


volumes:
  mosquitto_data:
    driver: local
  chronograf_data:
    driver: local
  influxdb_data:
    driver: local
  shared_data: